---
title: "zillow_augsynth"
author: "Timothy Majidzadeh"
date: "2025-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(dplyr)
library(augsynth)
```


```{r data, include=FALSE}
## Import Data
zillow_reg <- read.csv('../data/zillow_reg_data/zillow_data_reg_20250404.csv') %>%
  mutate(
    AffectedCityTime = AffectedCity * AffectedTime
  ) %>%
  filter(Year < 2020)

```

```{r augsynth, include=FALSE, warning=FALSE}
## Execute augsynth
treat_cities <- c(
  'Atlanta, GA',
  'Dallas, TX',
  'Phoenix, AZ',
  'Denver, CO',
  'Tampa, FL',
  'Washington, DC'
)

for (city in treat_cities){
  one_city_data = zillow_reg %>%
    filter((AffectedCity == 0) | (RegionName == city))
  syn <- augsynth(
      ZORI ~ AffectedCityTime, RegionName, TimeTrend, one_city_data, progfunc="None", SCM=T, t_int=35
    )
  syn_sum <- summary(syn, stat_func = function(x) abs(sum(x)))
  write.csv(syn_sum[['average_att']], file=paste0('../data/reg_results/syn_2015-2019_avg_att_', city, '.csv'))
  write.csv(syn_sum[['att']], file=paste0('../data/reg_results/syn_2015-2019_att_', city, '.csv'))
}
```

```{r alt_controls, include=FALSE, warning=FALSE}
# Use a reduced-size control group instead of using all non-treatment cities as the control group. Synthetic control can give a false-negative result if "unaffected" cities are in fact affected.
alt_control_cities <- c(
  'Minneapolis, MN',
  'San Diego, CA',
  'Miami, FL',
  'San Francisco, CA', 
  'Chicago, IL',
  'Detroit, MI', 
  'Los Angeles, CA',
  'New York, NY'
)

zillow_reg_alt_control <- zillow_reg %>%
  filter((AffectedCity == 1) | (RegionName %in% alt_control_cities))

for (city in treat_cities){
  one_city_data = zillow_reg_alt_control %>%
    filter((AffectedCity == 0) | (RegionName == city))
  syn <- augsynth(
      ZORI ~ AffectedCityTime, RegionName, TimeTrend, one_city_data, progfunc="None", SCM=T, t_int=35
    )
  syn_sum <- summary(syn, stat_func = function(x) abs(sum(x)))
  write.csv(syn_sum[['average_att']], file=paste0('../data/reg_results/syn_alt_con_2015-2019avg_att_', city, '.csv'))
  write.csv(syn_sum[['att']], file=paste0('../data/reg_results/syn_alt_con_2015-2019_att_', city, '.csv'))
}
```